# Generated by Django 4.2.5 on 2023-12-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doormot_property_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='for_sale_listed_properties',
            name='sub_commercial_property_type',
            field=models.CharField(blank=True, choices=[('SHP', 'Shopping Complex'), ('OS', 'Office Space'), ('SSHPU', 'Shop Units'), ('SCHL', 'School Building'), ('HSPTL', 'Hospital Building'), ('PTRLSTN', 'Petrol Station'), ('RSTRNT', 'Restaurant Building')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='to_let_listed_properties',
            name='sub_commercial_property_type',
            field=models.CharField(blank=True, choices=[('SHP', 'Shopping Complex'), ('OS', 'Office Space'), ('SSHPU', 'Shop Units'), ('SCHL', 'School Building'), ('HSPTL', 'Hospital Building'), ('PTRLSTN', 'Petrol Station'), ('RSTRNT', 'Restaurant Building')], default=None, max_length=50, null=True),
        ),
    ]
