# Generated by Django 4.2.5 on 2023-11-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doormot_property_listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to_let_listed_properties',
            old_name='time_of_upload',
            new_name='date_time_of_upload',
        ),
        migrations.RemoveField(
            model_name='to_let_listed_properties',
            name='date_of_upload',
        ),
        migrations.AlterField(
            model_name='for_sale_listed_properties',
            name='date_time_of_sale',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='to_let_listed_properties',
            name='is_available_for_lease',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=None, max_length=50),
        ),
    ]
