# Generated by Django 4.2.5 on 2023-11-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doormot_property_listing', '0002_rename_time_of_upload_to_let_listed_properties_date_time_of_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='for_sale_listed_properties',
            name='date_time_of_sale',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
