# Generated by Django 4.2.5 on 2023-10-30 11:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doormot_users_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Private_owner_profile',
            new_name='Individual_owner_profile',
        ),
    ]
