# Generated by Django 4.2.5 on 2023-10-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doormot_users_profiles', '0002_rename_private_owner_profile_individual_owner_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual_owner_profile',
            old_name='Private_owner_user',
            new_name='Individual_owner_profile',
        ),
    ]
