# Generated by Django 4.2.5 on 2023-11-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doormot_users_profiles', '0004_remove_individual_owner_profile_individual_owner_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Individual_owner_profile',
        ),
    ]
