# Generated by Django 4.2.5 on 2023-11-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doormot_reg_users', '0002_remove_doormot_user_independent_agent_details_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doormot_user_independent_agent',
            name='currently_logged_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_buyer',
            name='currently_logged_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_owner',
            name='currently_logged_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_tenant',
            name='currently_logged_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_official_agent',
            name='currently_logged_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_buyer',
            name='currently_logged_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_owner',
            name='currently_logged_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_tenant',
            name='currently_logged_in',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
