# Generated by Django 4.2.5 on 2023-12-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doormot_reg_users', '0003_alter_doormot_user_independent_agent_locked_account_count_down_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doormot_user_independent_agent',
            name='locked_account_count_down_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
