# Generated by Django 4.2.5 on 2023-12-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doormot_reg_users', '0004_alter_doormot_user_independent_agent_locked_account_count_down_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doormot_user_independent_agent',
            name='unhashed_recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
