# Generated by Django 4.2.5 on 2023-12-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doormot_reg_users', '0005_doormot_user_independent_agent_unhashed_recovery_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='doormot_user_individual_buyer',
            name='favorite_movie_title',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_buyer',
            name='last_name_of_favorite_high_school_teacher',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_buyer',
            name='locked_account_count_down_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_buyer',
            name='name_of_first_pet',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_buyer',
            name='name_of_high_school_attended',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_buyer',
            name='name_of_mother_place_of_birth',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_buyer',
            name='recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_buyer',
            name='recovery_salt',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_buyer',
            name='unhashed_recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_owner',
            name='favorite_movie_title',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_owner',
            name='last_name_of_favorite_high_school_teacher',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_owner',
            name='locked_account_count_down_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_owner',
            name='name_of_first_pet',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_owner',
            name='name_of_high_school_attended',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_owner',
            name='name_of_mother_place_of_birth',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_owner',
            name='recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_owner',
            name='recovery_salt',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_owner',
            name='unhashed_recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_tenant',
            name='favorite_movie_title',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_tenant',
            name='last_name_of_favorite_high_school_teacher',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_tenant',
            name='locked_account_count_down_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_tenant',
            name='name_of_first_pet',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_tenant',
            name='name_of_high_school_attended',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_tenant',
            name='name_of_mother_place_of_birth',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_tenant',
            name='recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_tenant',
            name='recovery_salt',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_individual_tenant',
            name='unhashed_recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_official_agent',
            name='favorite_movie_title',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_official_agent',
            name='last_name_of_favorite_high_school_teacher',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_official_agent',
            name='locked_account_count_down_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_official_agent',
            name='name_of_first_pet',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_official_agent',
            name='name_of_high_school_attended',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_official_agent',
            name='name_of_mother_place_of_birth',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_official_agent',
            name='recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_official_agent',
            name='recovery_salt',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_official_agent',
            name='unhashed_recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_buyer',
            name='current_ceo_pres_of_org',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_buyer',
            name='first_ceo_pres_of_org',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_buyer',
            name='founding_year_of_org',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_buyer',
            name='locked_account_count_down_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_buyer',
            name='official_mission_statement',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_buyer',
            name='org_first_office_location',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_buyer',
            name='recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_buyer',
            name='recovery_salt',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_buyer',
            name='unhashed_recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_owner',
            name='current_ceo_pres_of_org',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_owner',
            name='first_ceo_pres_of_org',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_owner',
            name='founding_year_of_org',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_owner',
            name='locked_account_count_down_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_owner',
            name='official_mission_statement',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_owner',
            name='org_first_office_location',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_owner',
            name='recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_owner',
            name='recovery_salt',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_owner',
            name='unhashed_recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_tenant',
            name='current_ceo_pres_of_org',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_tenant',
            name='first_ceo_pres_of_org',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_tenant',
            name='founding_year_of_org',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_tenant',
            name='locked_account_count_down_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_tenant',
            name='official_mission_statement',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_tenant',
            name='org_first_office_location',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_tenant',
            name='recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_tenant',
            name='recovery_salt',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='doormot_user_private_organization_tenant',
            name='unhashed_recovery_code',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
